; Copyright (c) 2026 Lukas Kraft; https://github.com/reboot-required
;
; Part of MazarbuLib-ESP32-Sample — demo project for MazarbuLib.
; SPDX-License-Identifier: MIT

[env:esp32dev]
platform     = espressif32
board        = esp32dev
framework    = arduino
monitor_speed = 115200
